vich_uploader:
    db_driver: orm

    mappings:
        ads:
            uri_prefix: '%ads_pic_dir%'
            upload_destination: '%kernel.project_dir%/public/uploads/ads'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

